In [1]:
!pip install torch

^C
  Using cached torch-2.7.1-cp312-cp312-win_amd64.whl.metadata (28 kB)
Using cached torch-2.7.1-cp312-cp312-win_amd64.whl (216.1 MB)


In [1]:
import torch
x = torch.empty(3)
print(x)

tensor([1.9353e+25, 1.9548e-42, 0.0000e+00])


In [2]:
x = torch.empty(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
x = torch.empty(2,2,3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [4]:
x = torch.rand(2,3)
print(x)

tensor([[0.9379, 0.5280, 0.7913],
        [0.3053, 0.5198, 0.1539]])


In [2]:
import torch
x = torch.zeros(2,2)
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [3]:
x = torch.ones(2,2)
print(x)
print(x.dtype)

tensor([[1., 1.],
        [1., 1.]])
torch.float32


In [4]:
x = torch.ones(2,2,dtype = torch.int)
print(x)
print(x.dtype)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)
torch.int32


In [5]:
x = torch.ones(2,2,dtype = torch.double)
print(x)
print(x.dtype)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
torch.float64


In [1]:
#Tensor Operations

import torch
x = torch.rand(3,3)
y = torch.rand(3,3)
print(x)
print(y)
z = x+y
print(z)


tensor([[0.3777, 0.7590, 0.7279],
        [0.1803, 0.9231, 0.9999],
        [0.7559, 0.2818, 0.6788]])
tensor([[0.0617, 0.5073, 0.3227],
        [0.7726, 0.4734, 0.0445],
        [0.1579, 0.0880, 0.6840]])
tensor([[0.4394, 1.2663, 1.0506],
        [0.9529, 1.3964, 1.0444],
        [0.9138, 0.3699, 1.3628]])


In [2]:
x = torch.rand(2,3)
y = torch.rand(2,3)
print(x)
print(y)
z = torch.add(x,y)
print(z)

tensor([[0.8470, 0.1006, 0.8609],
        [0.4584, 0.5508, 0.7120]])
tensor([[0.1197, 0.3360, 0.7366],
        [0.6364, 0.1624, 0.2650]])
tensor([[0.9667, 0.4366, 1.5975],
        [1.0948, 0.7132, 0.9770]])


In [3]:
x = torch.rand(2,3)
y = torch.rand(2,3)
print(x)
print(y)
y.add_(x)
print(y)


tensor([[0.1701, 0.4292, 0.4717],
        [0.6588, 0.7546, 0.0967]])
tensor([[0.1047, 0.1752, 0.7450],
        [0.0305, 0.3741, 0.5587]])
tensor([[0.2748, 0.6044, 1.2167],
        [0.6893, 1.1287, 0.6554]])


In [4]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.mul(x,y)
print(z)

tensor([[0.7455, 0.8518],
        [0.5865, 0.1713]])
tensor([[0.0196, 0.9547],
        [0.4496, 0.8404]])
tensor([[0.0146, 0.8132],
        [0.2637, 0.1440]])


In [5]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
z = torch.div(x,y)
print(z)

tensor([[0.1921, 0.6219],
        [0.4851, 0.9058]])
tensor([[0.1851, 0.5138],
        [0.4450, 0.5220]])
tensor([[1.0377, 1.2104],
        [1.0901, 1.7354]])


In [6]:
x = torch.rand(5,3)
print(x)
print(x[:,2])
print(x[3,:])

tensor([[0.8859, 0.8795, 0.8249],
        [0.3370, 0.8005, 0.4037],
        [0.8360, 0.5839, 0.9111],
        [0.8870, 0.0224, 0.4171],
        [0.0870, 0.5963, 0.5002]])
tensor([0.8249, 0.4037, 0.9111, 0.4171, 0.5002])
tensor([0.8870, 0.0224, 0.4171])


In [7]:
x = torch.rand(4,4)
print(x)
y = x.view(16)
print(y)

tensor([[0.5176, 0.1312, 0.9208, 0.6040],
        [0.9238, 0.6184, 0.9908, 0.0706],
        [0.9024, 0.6200, 0.7108, 0.5547],
        [0.8777, 0.2242, 0.3138, 0.5929]])
tensor([0.5176, 0.1312, 0.9208, 0.6040, 0.9238, 0.6184, 0.9908, 0.0706, 0.9024,
        0.6200, 0.7108, 0.5547, 0.8777, 0.2242, 0.3138, 0.5929])


In [10]:
x = torch.rand(6,6)
print(x)
y = x.view(-1,12)
print(y)
print(y.size())

tensor([[0.2012, 0.6459, 0.2760, 0.5661, 0.2002, 0.9985],
        [0.8655, 0.9207, 0.1703, 0.2391, 0.6393, 0.6055],
        [0.8857, 0.0484, 0.1201, 0.3884, 0.1072, 0.1293],
        [0.2910, 0.4526, 0.1639, 0.9681, 0.7645, 0.7308],
        [0.7149, 0.5415, 0.7053, 0.0447, 0.7303, 0.5976],
        [0.6084, 0.5601, 0.9742, 0.4228, 0.4590, 0.3866]])
tensor([[0.2012, 0.6459, 0.2760, 0.5661, 0.2002, 0.9985, 0.8655, 0.9207, 0.1703,
         0.2391, 0.6393, 0.6055],
        [0.8857, 0.0484, 0.1201, 0.3884, 0.1072, 0.1293, 0.2910, 0.4526, 0.1639,
         0.9681, 0.7645, 0.7308],
        [0.7149, 0.5415, 0.7053, 0.0447, 0.7303, 0.5976, 0.6084, 0.5601, 0.9742,
         0.4228, 0.4590, 0.3866]])
torch.Size([3, 12])


In [11]:
x = torch.tensor([[2,3],[4,5]])
print(x)
x_ones = torch.ones_like(x)
print(x_ones)

tensor([[2, 3],
        [4, 5]])
tensor([[1, 1],
        [1, 1]])


In [12]:
x = torch.tensor([[2,3],[4,5]])
print(x)
x_rand = torch.rand_like(x, dtype = torch.float)
print(x_rand)

tensor([[2, 3],
        [4, 5]])
tensor([[0.4799, 0.0690],
        [0.1482, 0.6934]])


In [13]:
import numpy as np
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [14]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
